spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bankdb
    username: bankuser
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080
